### ISSUE TITLE
Flask Security Architecture 

### ISSUE THREAD

**Issue by emysa341** [berkus/uvvy#12]
Sorry there is no way I could contact you guys because of no private messaging. I want to discuss something regarding Fluke security architecture. I want to implement flask security architecture in java where I can inject difference security policies. So all in all at the moment I need which parts of code in meta OS implement FLASK SA. Please contact me on skype : ammad.amu36 or email : ammad.emy36@gmail.com.

**Comment by berkus** [comment]
Not related to uvvy.
